name: manioc_ai
description: Projet Flutter de détection du manioc avec IA
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  # http: ^1.4.0
  # path_provider: ^2.0.15
  # path: ^1.8.3
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  tflite_flutter: ^0.11.0
  camera: ^0.11.1
  image: ^4.5.4
  mockito: ^5.4.6
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  flutter_svg: ^2.1.0

  






flutter:
  uses-material-design: true
  assets:
    - assets/cassava_model.tflite
    - assets/labels.txt
    - assets/LOGO_SBG.png
